### ISSUE TITLE
glowsoup gives regular bowl when eaten

### ISSUE THREAD

**Issue by scp-3537** [CalaMariGold/TREPIDATION#10]

**Comment by CalaMariGold** [comment]
also need to fix recipe so it only accepts glowood bowl

**Comment by CalaMariGold** [comment]
"glowsoup gives regular bowl when eaten"

I couldn't reproduce this on my end. It gave me a glowood bowl.

**Comment by CalaMariGold** [comment]
Fixed in 0.3.1
