### ISSUE TITLE
Soul Compass given to every player on the server

### ISSUE THREAD

**Issue by godlyvex5** [CalaMariGold/TREPIDATION#12]
=======Pack Info======= 

IGN: Godlyvex5
Pack Version: 0.3.0
MC Version: 1.12.2
Forge Version: 14.23.5.2860
Mods Loaded: 189

=======System Info======= 

Operating System: Windows 10
Java: 1.8.0_51 64bit
CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
Display: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
Mem:  44% 1623/3641MB
Allocated:  95% 3469MB

======= Issue ======= 
 
Title: soul compass multiplayer bug, hotkeys
 
--------------------------- 
Description: getting soul compass when my friend dies, can't use hotkeys 1-9 or dodge while holding shift to sprint

=======CrashLog======= 
No CrashLog

**Comment by CalaMariGold** [comment]
Thanks for reporting the soul compass issue, as for the hotkeys, you don't need to hold it to sprint. Just press it once.

**Comment by CalaMariGold** [comment]
Fixed in 0.3.1
