### ISSUE TITLE
timer count not resetting 

### ISSUE THREAD

**Issue by st-cky** [CalaMariGold/TREPIDATION#14]
=======Pack Info======= 

IGN: stzz
Pack Version: 0.3.2
MC Version: 1.12.2
Forge Version: 14.23.5.2860
Mods Loaded: 192

=======System Info======= 

Operating System: Windows 10
Java: 1.8.0_352 64bit
CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700KF
Display: NVIDIA GeForce RTX 2060/PCIe/SSE2
Mem:  69% 4471/6425MB
Allocated:  100% 6425MB

======= Issue ======= 
 
Title: timer count not resetting 
 
--------------------------- 
Description: using ingame reset run button does not reset the used timer count from previous runs 

=======CrashLog======= 
No CrashLog

**Comment by CalaMariGold** [comment]
Fixed in v0.3.3
