### ISSUE TITLE
[BUG] Any damage resets player's momentum, including fire tick

### ISSUE THREAD

**Issue by CalaMariGold** [CalaMariGold/TREPIDATION#16]
When moving horizontally through the air via dodging, any damage the player receives will immediately send them downward, resetting any momentum the player built up.

Possibly related mods:
- Elenai Dodge 2

**Comment by CalaMariGold** [comment]
https://github.com/ACGaming/UniversalTweaks/issues/191

**Comment by KxttyKxt** [comment]
This is a vanilla bug/feature. As such, I have no idea if Elenai Dodge can bypass it.

**Comment by CalaMariGold** [comment]
Fixed in 0.4 (not yet released)

Tangentially related, being plummeted into lava when just above it has also been fixed
