### ISSUE TITLE
unable to attack scorpion when being held

### ISSUE THREAD

**Issue by blue0005** [CalaMariGold/TREPIDATION#20]
=======Pack Info======= 

IGN: scorched1919
Pack Version: 0.4.1
MC Version: 1.12.2
Forge Version: 14.23.5.2860
Mods Loaded: 205

=======System Info======= 

Operating System: Windows 10
Java: 1.8.0_51 64bit
CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
Display: NVIDIA GeForce GTX 1650/PCIe/SSE2
Mem:  33% 2101/6229MB
Allocated:  96% 5992MB

======= Issue ======= 
 
Title: unable to attack scorpion when being held
 
--------------------------- 
Description: can't attack scorpion when it grabs you

=======CrashLog======= 
No CrashLog

**Comment by CalaMariGold** [comment]
I'm gonna leave this as intended. it'll make them more scary and make players shoot them with bows. maybe they're holding your arms down so you cant attack
