### ISSUE TITLE
Changing some volume sliders doesn't change the volume unless its turned all the way off

### ISSUE THREAD

**Issue by CoolJoe2003** [CalaMariGold/TREPIDATION#23]
Singleplayer and multiplayer. This specifically applies to the music and biomes sliders (the lightning in the surface is very loud), but some still work like the master volume slider with the button pressing sound when navigating through the menu, as well as the footsteps and blocks volume sliders.

**Comment by CalaMariGold** [comment]
Should be fixed next version.
