### ISSUE TITLE
Fire Charge java.lang.NullPointerException 

### ISSUE THREAD

**Issue by ghost** [CalaMariGold/TREPIDATION#5]
=======Pack Info======= 

IGN: 4D1OSZ
Pack Version: 0.2.4
MC Version: 1.12.2
Forge Version: 14.23.5.2860
Mods Loaded: 172

=======System Info======= 

Operating System: Windows 10
Java: 1.8.0_51 64bit
CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
Display: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
Mem:  19% 1382/7196MB
Allocated:  75% 5445MB

======= Issue ======= 
 
Title: Fire Charge java.lang.NullPointerException 
 
--------------------------- 
Description: After using all Fire Charges on inventory slot, the chat spews out java.lang.NullPointerException error.
After looking in the latest.log play turns out OptiFine makes some model registering error. The mentioned log will be in the attachments.

=======CrashLog======= 
No CrashLog

=======Attachment=======
[latest.log](https://github.com/CalaMariGold/TREPIDATION/files/9223052/latest.log)

![Screenshot2022-07-29 220401](https://user-images.githubusercontent.com/109760956/181840329-e21bef67-5191-4896-b8ab-90735af4217e.png)

https://user-images.githubusercontent.com/109760956/181840345-30ee23d2-2712-4bfa-aeb6-0619ddf2f325.mp4

**Comment by CalaMariGold** [comment]
Thank you for this detailed report! I sent it over to the Charge Thrower GitHub

**Comment by CalaMariGold** [comment]
Fixed in the next update (0.4) by just removing the error log. The error doesn't seem to actually affect anything
