### ISSUE TITLE
[Server] Universal Tweaks Error

### ISSUE THREAD

**Issue by Xziros** [CalaMariGold/TREPIDATION#6]
Hello i can't connect to the server with the modpack here is the error when i login : 
https://mclo.gs/azZyJCl

Thanks you !

**Comment by Xziros** [comment]
Hello, 
the error is still here with the new patch.
https://mclo.gs/QOtIcWl
Thanks you !

**Comment by CalaMariGold** [comment]
This will be fixed in a future update. Temporary fix is to go into the config for Universal Tweaks and disable "Max Health Tweaks" for both server and client.

**Comment by CalaMariGold** [comment]
Fixed in 0.2.9 https://github.com/CalaMariGold/TREPIDATION/commit/938a5c06f60c38e8fe790503e9bce8f355e9f755#diff-90277e80b9e0b01c651609ad75040e36ec15bdb2651d97c2557abab55960e860
